FROM node:20-alpine AS development
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY prisma ./prisma 
COPY . . 
RUN npx prisma generate --schema=./prisma/schema.prisma
RUN npm run build
CMD [ "npm", "run", "start:prod" ]


FROM node:20-alpine AS production

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --production

COPY prisma ./prisma

COPY --from=development /usr/src/app/dist ./dist
COPY --from=development /usr/src/app/prisma ./prisma
RUN npx prisma generate --schema=./prisma/schema.prisma


CMD [ "node", "dist/main" ]
